version: '2'
services:
  eslacki-elasticsearch:
    image: elasticsearch:latest
    networks:
      eslacki:
        aliases:
          - elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  eslacki-kibana:
    image: kibana:latest
    networks:
      eslacki:
        aliases:
          - kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

networks:
  eslacki:
